"""
Build .ipynb files for the Fabric Shortcut Observability project from inline cell definitions.
Run:  python build_notebooks.py
"""
from __future__ import annotations
import json, os, pathlib

OUT = pathlib.Path(__file__).parent

def md(*lines):  return {"cell_type": "markdown", "metadata": {}, "source": _join(lines)}
def code(*lines): return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": _join(lines)}
def _join(lines):
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + ("\n" if i < len(parts)-1 else "") for i, p in enumerate(parts)]

def nb(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Synapse PySpark", "language": "python", "name": "synapse_pyspark"},
            "language_info": {"name": "python"},
            "microsoft": {"language": "python", "ms_spell_check": {"ms_spell_check_language": "en"}},
            "nteract": {"version": "nteract-front-end@1.0.0"}
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

# ---------------- shared config-loader cell (reused) ----------------
LOAD_CFG = code(
    "import json, os",
    "from pyspark.sql import functions as F",
    "",
    "# When run inside Fabric, the notebook resource folder contains config.json.",
    "# Fabric exposes notebook-attached files via mssparkutils / notebookutils.",
    "try:",
    "    import notebookutils  # type: ignore",
    "    cfg_path = notebookutils.nbResPath + '/builtin/config.json'",
    "    if not os.path.exists(cfg_path):",
    "        # Fallback: lakehouse Files/config.json",
    "        cfg_path = '/lakehouse/default/Files/config.json'",
    "except Exception:",
    "    cfg_path = './config.json'",
    "",
    "with open(cfg_path, 'r', encoding='utf-8') as f:",
    "    CFG = json.load(f)",
    "",
    "OBS_WS  = CFG['observability_workspace_name']",
    "OBS_LH  = CFG['observability_lakehouse_name']",
    "TBL     = CFG['tables']",
    "API     = CFG['fabric_api']",
    "# monitored_workspaces is a list of workspace display names (strings).",
    "# Backwards-compat: also accept the old [{workspace_name: ...}] shape.",
    "_raw_mon = CFG['monitored_workspaces']",
    "MONITOR = [m if isinstance(m, str) else m['workspace_name'] for m in _raw_mon]",
    "INGEST  = CFG['ingestion']",
    "print(f'Observability workspace : {OBS_WS}')",
    "print(f'Observability lakehouse : {OBS_LH}')",
    "print(f'Monitored workspaces    : {MONITOR}')",
)

# ---------------- 01_setup ----------------
nb01 = nb([
    md("# 01 — Setup",
       "",
       "Creates the Delta tables that the rest of the project writes to. Run **once** after the observability lakehouse exists and `config.json` has been uploaded to `Files/config.json` of the observability lakehouse (or to the notebook resource folder)."),
    LOAD_CFG,
    md("## Create empty Delta tables (idempotent)"),
    code(
        "from pyspark.sql.types import *",
        "",
        "bronze_schema = StructType([",
        "    StructField('event_date', DateType()),",
        "    StructField('source_workspace_name', StringType()),",
        "    StructField('workspaceId', StringType()),",
        "    StructField('itemId', StringType()),",
        "    StructField('itemType', StringType()),",
        "    StructField('tenantId', StringType()),",
        "    StructField('executingPrincipalId', StringType()),",
        "    StructField('executingUPN', StringType()),",
        "    StructField('executingPrincipalType', StringType()),",
        "    StructField('correlationId', StringType()),",
        "    StructField('operationName', StringType()),",
        "    StructField('operationCategory', StringType()),",
        "    StructField('accessStartTime', TimestampType()),",
        "    StructField('accessEndTime', TimestampType()),",
        "    StructField('originatingApp', StringType()),",
        "    StructField('serviceEndpoint', StringType()),",
        "    StructField('Resource', StringType()),",
        "    StructField('capacityId', StringType()),",
        "    StructField('httpStatusCode', IntegerType()),",
        "    StructField('isShortcut', BooleanType()),",
        "    StructField('accessedViaResource', StringType()),",
        "    StructField('callerIPAddress', StringType()),",
        "    StructField('contentLength', LongType()),",
        "    StructField('_source_file', StringType()),",
        "    StructField('_ingested_at', TimestampType()),",
        "])",
        "",
        "shortcut_schema = StructType([",
        "    StructField('scanned_at', TimestampType()),",
        "    StructField('source_workspace_name', StringType()),",
        "    StructField('source_workspace_id', StringType()),",
        "    StructField('source_item_name', StringType()),",
        "    StructField('source_item_id', StringType()),",
        "    StructField('shortcut_name', StringType()),",
        "    StructField('shortcut_path', StringType()),",
        "    StructField('shortcut_full_path', StringType()),",
        "    StructField('target_type', StringType()),",
        "    StructField('target_workspace_id', StringType()),",
        "    StructField('target_workspace_name', StringType()),",
        "    StructField('target_item_id', StringType()),",
        "    StructField('target_item_name', StringType()),",
        "    StructField('target_path', StringType()),",
        "    StructField('target_connection_id', StringType()),",
        "    StructField('target_location', StringType()),",
        "    StructField('target_subpath', StringType()),",
        "    StructField('target_raw_json', StringType()),",
        "])",
        "",
        "for name, schema in [(TBL['bronze'], bronze_schema), (TBL['dim_shortcuts'], shortcut_schema)]:",
        "    if not spark.catalog.tableExists(name):",
        "        (spark.createDataFrame([], schema)",
        "             .write.format('delta').mode('overwrite').saveAsTable(name))",
        "        print(f'Created table: {name}')",
        "    else:",
        "        print(f'Exists       : {name}')",
        "",
        "# silver is created by 04_silver_enriched_access on first run (CTAS)",
        "print('Setup complete.')",
    ),
])

# ---------------- 02_bronze_union_diagnostics ----------------
nb02 = nb([
    md("# 02 — Bronze: union OneLake diagnostic JSON",
       "",
       "For every workspace listed in `config.json → monitored_workspaces[]`, the notebook:",
       "",
       "1. Lists all lakehouses in that workspace via the Fabric REST API.",
       "2. Probes each lakehouse for a `Files/DiagnosticLogs/OneLake/Workspaces/` folder — the canonical layout written when OneLake diagnostics is enabled.",
       "3. Reads hourly `PT1H.json` partitions in the lookback window from every lakehouse where that folder exists, and merges into `bronze_onelake_raw_events`.",
       "",
       "**You only need to list workspace names** in `config.json` — the diagnostics lakehouse(s) are auto-detected.",
       "",
       "Idempotent: dedupes on the natural key `(correlationId, accessStartTime, operationName, Resource)` within the lookback window."),
    LOAD_CFG,
    md("## Discover diagnostics-enabled lakehouses in each monitored workspace"),
    code(
        "import requests",
        "from datetime import datetime, timedelta, timezone",
        "import notebookutils  # type: ignore",
        "",
        "TOKEN = notebookutils.credentials.getToken(API['token_audience'])",
        "HEADERS = {'Authorization': f'Bearer {TOKEN}'}",
        "BASE = API['base_url'].rstrip('/')",
        "",
        "def fab_get(path, params=None):",
        "    r = requests.get(f'{BASE}{path}', headers=HEADERS, params=params, timeout=60)",
        "    r.raise_for_status()",
        "    return r.json()",
        "",
        "def list_paged(path, params=None):",
        "    items, ct = [], None",
        "    while True:",
        "        p = dict(params or {})",
        "        if ct: p['continuationToken'] = ct",
        "        data = fab_get(path, p)",
        "        items.extend(data.get('value', []))",
        "        ct = data.get('continuationToken')",
        "        if not ct: break",
        "    return items",
        "",
        "all_workspaces = list_paged('/workspaces')",
        "ws_by_name = {w['displayName']: w for w in all_workspaces}",
        "",
        "DIAG_ROOT = INGEST.get('diagnostics_root_path', 'Files/DiagnosticLogs/OneLake').strip('/')",
        "",
        "def onelake_path(ws_id, item_id, suffix=''):",
        "    return f'abfss://{ws_id}@onelake.dfs.fabric.microsoft.com/{item_id}/{suffix}'.rstrip('/')",
        "",
        "def has_diagnostics(ws_id, item_id):",
        "    probe = onelake_path(ws_id, item_id, f'{DIAG_ROOT}/Workspaces')",
        "    try:",
        "        entries = notebookutils.fs.ls(probe)",
        "        return len(entries) > 0",
        "    except Exception:",
        "        return False",
        "",
        "diag_lakehouses = []  # list of dicts: {workspace_name, workspace_id, lakehouse_name, lakehouse_id, root}",
        "for ws_name in MONITOR:",
        "    ws = ws_by_name.get(ws_name)",
        "    if not ws:",
        "        print(f'  ! skipping workspace (not found / no access): {ws_name}')",
        "        continue",
        "    lakehouses = list_paged(f\"/workspaces/{ws['id']}/items\", {'type': 'Lakehouse'})",
        "    enabled = []",
        "    for lh in lakehouses:",
        "        if has_diagnostics(ws['id'], lh['id']):",
        "            enabled.append(lh)",
        "            diag_lakehouses.append({",
        "                'workspace_name': ws_name,",
        "                'workspace_id':   ws['id'],",
        "                'lakehouse_name': lh['displayName'],",
        "                'lakehouse_id':   lh['id'],",
        "                'root':           onelake_path(ws['id'], lh['id'], DIAG_ROOT),",
        "            })",
        "    print(f'  {ws_name}: {len(lakehouses)} lakehouse(s), {len(enabled)} with OneLake diagnostics enabled')",
        "    for lh in enabled:",
        "        print(f\"      - {lh['displayName']}\")",
        "",
        "if not diag_lakehouses:",
        "    print('No diagnostics-enabled lakehouses found in monitored workspaces. Nothing to ingest.')",
    ),
    md("## Build list of source paths"),
    code(
        "now = datetime.now(timezone.utc)",
        "lookback = timedelta(hours=int(INGEST['lookback_hours']))",
        "",
        "# Build hourly partitions to scan (avoids whole-tree listing)",
        "hours = []",
        "t = now - lookback",
        "while t <= now:",
        "    hours.append(t)",
        "    t += timedelta(hours=1)",
        "",
        "paths = []  # list of (source_workspace_name, abfss_glob)",
        "for d in diag_lakehouses:",
        "    base = f\"{d['root']}/Workspaces/*\"  # glob over the *target* workspace id partition",
        "    for h in hours:",
        "        glob = (f'{base}/'",
        "                f'y={h.year:04d}/m={h.month:02d}/d={h.day:02d}/h={h.hour:02d}/m=*/PT1H.json')",
        "        paths.append((d['workspace_name'], glob))",
        "",
        "print(f'Will scan {len(paths)} hourly partitions across {len(diag_lakehouses)} diagnostics lakehouse(s).')",
    ),
    md("## Read JSON, normalize, and dedupe"),
    code(
        "from pyspark.sql import functions as F, types as T",
        "",
        "def safe_read(glob):",
        "    try:",
        "        # OneLake / Azure diagnostic PT1H.json files are NDJSON (one event per line).",
        "        # Do NOT set multiLine=true — that would parse each file as a single JSON",
        "        # document and dump everything into _corrupt_record.",
        "        return (spark.read",
        "                    .option('recursiveFileLookup', 'false')",
        "                    .json(glob)",
        "                    .withColumn('_source_file', F.input_file_name()))",
        "    except Exception as e:",
        "        return None",
        "",
        "frames = []",
        "for ws_name, glob in paths:",
        "    df = safe_read(glob)",
        "    if df is None or df.rdd.isEmpty():",
        "        continue",
        "    df = df.withColumn('source_workspace_name', F.lit(ws_name))",
        "    frames.append(df)",
        "",
        "if not frames:",
        "    print('No new diagnostic events in lookback window. Exiting.')",
        "    dbutils.notebook.exit('no-data') if 'dbutils' in dir() else None",
        "else:",
        "    raw = frames[0]",
        "    for f_ in frames[1:]:",
        "        raw = raw.unionByName(f_, allowMissingColumns=True)",
        "",
        "    # OneLake diagnostic logs use the Azure Monitor envelope: top-level",
        "    # {category, time, resourceId, id, type, data:{...}}.  All event fields",
        "    # live under data.* with mixed casing (executingUpn, callerIpAddress,",
        "    # resource).  Flatten and rename to the canonical names used downstream.",
        "    if 'data' in raw.columns:",
        "        raw = raw.select(",
        "            F.col('source_workspace_name'),",
        "            F.col('_source_file'),",
        "            F.col('time').alias('_envelope_time'),",
        "            F.col('data.workspaceId').alias('workspaceId'),",
        "            F.col('data.itemId').alias('itemId'),",
        "            F.col('data.itemType').alias('itemType'),",
        "            F.col('data.tenantId').alias('tenantId'),",
        "            F.col('data.executingPrincipalId').alias('executingPrincipalId'),",
        "            F.col('data.executingUpn').alias('executingUPN'),",
        "            F.col('data.executingPrincipalType').alias('executingPrincipalType'),",
        "            F.col('data.correlationId').alias('correlationId'),",
        "            F.col('data.operationName').alias('operationName'),",
        "            F.col('data.operationCategory').alias('operationCategory'),",
        "            F.col('data.accessStartTime').alias('accessStartTime'),",
        "            F.col('data.accessEndTime').alias('accessEndTime'),",
        "            F.col('data.originatingApp').alias('originatingApp'),",
        "            F.col('data.serviceEndpoint').alias('serviceEndpoint'),",
        "            F.col('data.resource').alias('Resource'),",
        "            F.col('data.capacityId').alias('capacityId'),",
        "            F.col('data.httpStatusCode').alias('httpStatusCode'),",
        "            F.col('data.isShortcut').alias('isShortcut'),",
        "            F.col('data.accessedViaResource').alias('accessedViaResource'),",
        "            F.col('data.callerIpAddress').alias('callerIPAddress'),",
        "            # contentLength is not emitted by OneLake diagnostics today;",
        "            # add as null so the bronze schema stays stable.",
        "            F.lit(None).cast('long').alias('contentLength'),",
        "        )",
        "",
        "    # Defensive cast — make sure every expected column exists",
        "    select_cols = ['workspaceId','itemId','itemType','tenantId',",
        "        'executingPrincipalId','executingUPN','executingPrincipalType',",
        "        'correlationId','operationName','operationCategory',",
        "        'accessStartTime','accessEndTime','originatingApp','serviceEndpoint',",
        "        'Resource','capacityId','httpStatusCode','isShortcut',",
        "        'accessedViaResource','callerIPAddress','contentLength']",
        "    for c in select_cols:",
        "        if c not in raw.columns:",
        "            raw = raw.withColumn(c, F.lit(None))",
        "",
        "    norm = (raw",
        "        .withColumn('accessStartTime', F.to_timestamp('accessStartTime'))",
        "        .withColumn('accessEndTime',   F.to_timestamp('accessEndTime'))",
        "        .withColumn('httpStatusCode',  F.col('httpStatusCode').cast('int'))",
        "        .withColumn('isShortcut',      F.col('isShortcut').cast('boolean'))",
        "        .withColumn('contentLength',   F.col('contentLength').cast('long'))",
        "        .withColumn('event_date',      F.to_date('accessStartTime'))",
        "        .withColumn('_ingested_at',    F.current_timestamp())",
        "        .select('event_date','source_workspace_name', *select_cols, '_source_file','_ingested_at')",
        "    )",
        "",
        "    # MERGE into bronze keyed by natural key",
        "    norm.createOrReplaceTempView('incoming_bronze')",
        "    spark.sql(f'''",
        "        MERGE INTO {TBL['bronze']} t",
        "        USING (SELECT * FROM incoming_bronze) s",
        "        ON  t.correlationId   <=> s.correlationId",
        "        AND t.accessStartTime <=> s.accessStartTime",
        "        AND t.operationName   <=> s.operationName",
        "        AND t.Resource        <=> s.Resource",
        "        WHEN NOT MATCHED THEN INSERT *",
        "    ''')",
        "    print('Bronze merge complete. Row count delta:')",
        "    spark.sql(f'SELECT COUNT(*) AS rows FROM {TBL[chr(34)+chr(98)+chr(114)+chr(111)+chr(110)+chr(122)+chr(101)+chr(34)]}').show() if False else None",
        "    print(spark.table(TBL['bronze']).count(), 'total rows in bronze')",
    ),
])

# ---------------- 03_dim_shortcuts_map ----------------
nb03 = nb([
    md("# 03 — Dim: shortcut map (Fabric REST → Delta)",
       "",
       "For every monitored workspace, lists every lakehouse via `GET /v1/workspaces/{ws}/items?type=Lakehouse`, calls `GET /v1/workspaces/{ws}/items/{item}/shortcuts` for each, and **overwrites** `dim_shortcut_map` with the current snapshot of all shortcuts.",
       "",
       "**Auth:** `notebookutils.credentials.getToken('pbi')` — runs as the user / service principal executing the notebook. That identity needs `Contributor` (or higher) on each monitored workspace."),
    LOAD_CFG,
    code(
        "import requests, json",
        "from datetime import datetime, timezone",
        "from pyspark.sql import functions as F, Row",
        "",
        "import notebookutils  # type: ignore",
        "TOKEN = notebookutils.credentials.getToken(API['token_audience'])",
        "HEADERS = {'Authorization': f'Bearer {TOKEN}'}",
        "BASE = API['base_url'].rstrip('/')",
        "",
        "def fab_get(path, params=None):",
        "    r = requests.get(f'{BASE}{path}', headers=HEADERS, params=params, timeout=60)",
        "    r.raise_for_status()",
        "    return r.json()",
        "",
        "def list_paged(path, params=None):",
        "    items, ct = [], None",
        "    while True:",
        "        p = dict(params or {})",
        "        if ct: p['continuationToken'] = ct",
        "        data = fab_get(path, p)",
        "        items.extend(data.get('value', []))",
        "        ct = data.get('continuationToken')",
        "        if not ct: break",
        "    return items",
    ),
    md("## Resolve workspace names → IDs"),
    code(
        "all_workspaces = list_paged('/workspaces')",
        "ws_by_name = {w['displayName']: w for w in all_workspaces}",
    ),
    md("## Pull shortcuts from every lakehouse in each monitored workspace"),
    code(
        "scanned_at = datetime.now(timezone.utc)",
        "rows = []",
        "for ws_name in MONITOR:",
        "    ws = ws_by_name.get(ws_name)",
        "    if not ws:",
        "        print(f'  ! skipping workspace (not found / no access): {ws_name}')",
        "        continue",
        "    lakehouses = list_paged(f\"/workspaces/{ws['id']}/items\", {'type': 'Lakehouse'})",
        "    print(f'  {ws_name}: {len(lakehouses)} lakehouse(s)')",
        "    for lh in lakehouses:",
        "        lh_name = lh['displayName']",
        "        try:",
        "            shortcuts = list_paged(f\"/workspaces/{ws['id']}/items/{lh['id']}/shortcuts\")",
        "        except Exception as e:",
        "            print(f'    ! {lh_name}: failed to list shortcuts: {e}')",
        "            continue",
        "        if not shortcuts:",
        "            continue",
        "        print(f'    {lh_name}: {len(shortcuts)} shortcut(s)')",
        "        for sc in shortcuts:",
        "            tgt = sc.get('target', {}) or {}",
        "            ttype = tgt.get('type')",
        "            ol = tgt.get('oneLake') or {}",
        "            adls = tgt.get('adlsGen2') or {}",
        "            s3 = tgt.get('amazonS3') or {}",
        "            blob = tgt.get('azureBlobStorage') or {}",
        "            gcs = tgt.get('googleCloudStorage') or {}",
        "            ext = adls or s3 or blob or gcs",
        "            rows.append({",
        "                'scanned_at': scanned_at,",
        "                'source_workspace_name': ws_name,",
        "                'source_workspace_id': ws['id'],",
        "                'source_item_name': lh_name,",
        "                'source_item_id': lh['id'],",
        "                'shortcut_name': sc.get('name'),",
        "                'shortcut_path': sc.get('path'),",
        "                'shortcut_full_path': f\"{sc.get('path','').rstrip('/')}/{sc.get('name','')}\",",
        "                'target_type': ttype,",
        "                'target_workspace_id': ol.get('workspaceId'),",
        "                'target_workspace_name': None,  # filled in below for OneLake targets",
        "                'target_item_id':      ol.get('itemId'),",
        "                'target_item_name':    None,  # filled in below for OneLake targets",
        "                'target_path':         ol.get('path') or ext.get('subpath'),",
        "                'target_connection_id': (ext or {}).get('connectionId'),",
        "                'target_location':      (ext or {}).get('location'),",
        "                'target_subpath':       (ext or {}).get('subpath'),",
        "                'target_raw_json': json.dumps(tgt, default=str),",
        "            })",
        "",
        "print(f'Total shortcuts scanned: {len(rows)}')",
        "",
        "# --- Resolve target workspace/item names for OneLake-type shortcuts ---",
        "# Build a workspaceId -> name map from the workspaces we already listed,",
        "# plus on-demand for any target workspace not already known.",
        "ws_id_to_name = {w['id']: w['displayName'] for w in all_workspaces}",
        "target_ws_ids = {r['target_workspace_id'] for r in rows if r.get('target_workspace_id')}",
        "",
        "item_name_cache = {}  # (workspace_id, item_id) -> displayName",
        "for tgt_ws_id in target_ws_ids:",
        "    # Resolve workspace name if we don't have it (cross-tenant or workspaces",
        "    # the caller can see only via the items listing).",
        "    if tgt_ws_id not in ws_id_to_name:",
        "        try:",
        "            w = fab_get(f'/workspaces/{tgt_ws_id}')",
        "            ws_id_to_name[tgt_ws_id] = w.get('displayName')",
        "        except Exception as e:",
        "            print(f'  ! cannot resolve target workspace {tgt_ws_id}: {e}')",
        "            continue",
        "    # List items once per target workspace and cache (id -> displayName).",
        "    try:",
        "        for it in list_paged(f'/workspaces/{tgt_ws_id}/items'):",
        "            item_name_cache[(tgt_ws_id, it['id'])] = it['displayName']",
        "    except Exception as e:",
        "        print(f'  ! cannot list items in target workspace {tgt_ws_id}: {e}')",
        "",
        "for r in rows:",
        "    tw = r.get('target_workspace_id')",
        "    ti = r.get('target_item_id')",
        "    if tw:",
        "        r['target_workspace_name'] = ws_id_to_name.get(tw)",
        "    if tw and ti:",
        "        r['target_item_name'] = item_name_cache.get((tw, ti))",
    ),
    md("## Overwrite dim_shortcut_map with current snapshot",
       "",
       "Every run replaces the table with the latest set of shortcuts returned by the Fabric REST API. There is no history retained."),
    code(
        "from pyspark.sql.types import *",
        "",
        "if not rows:",
        "    print('No shortcuts found. dim_shortcut_map left unchanged.')",
        "else:",
        "    incoming = spark.createDataFrame(rows)",
        "    (incoming.write.format('delta')",
        "        .mode('overwrite').option('overwriteSchema','true')",
        "        .saveAsTable(TBL['dim_shortcuts']))",
        "    print(f\"dim_shortcut_map overwritten. Row count: {spark.table(TBL['dim_shortcuts']).count()}\")",
    ),
])

# ---------------- 04_silver_enriched_access ----------------
nb04 = nb([
    md("# 04 — Silver: enrich access events with shortcut target",
       "",
       "Joins bronze events (where `isShortcut = true`) against `dim_shortcut_map` (current snapshot) to resolve each access to its underlying target. Native (non-shortcut) events are excluded from this join."),
    LOAD_CFG,
    code(
        "from pyspark.sql import functions as F",
        "",
        "bronze = spark.table(TBL['bronze'])",
        "dim    = spark.table(TBL['dim_shortcuts'])",
        "",
        "# Extract <workspaceItemPrefix> from accessedViaResource. The shortcut is stored",
        "# under <ItemName>.<ItemType>/<path>/<name>, so we strip the leading <Item.Type>/",
        "# and compare against shortcut_full_path.",
        "evt = (bronze",
        "    .where(F.col('isShortcut') == True)",
        "    .withColumn('accessed_path_no_item',",
        "        F.regexp_replace(F.col('accessedViaResource'), r'^[^/]+/', ''))",
        ")",
        "",
        "# Join against the current dim snapshot.",
        "# Match d -> e by composing the dim side as",
        "#   <source_workspace_id>/<source_item_id><shortcut_full_path>",
        "# and checking the bronze event's accessed_path_no_item starts with it.",
        "j = (evt.alias('e').join(",
        "        dim.alias('d'),",
        "        F.col('e.accessed_path_no_item').startswith(",
        "            F.concat(F.col('d.source_workspace_id'), F.lit('/'),",
        "                     F.col('d.source_item_id'),",
        "                     F.col('d.shortcut_full_path'))),",
        "        'left'",
        "    ))",
        "",
        "enriched = j.select(",
        "    F.col('e.event_date'),",
        "    F.col('e.source_workspace_name').alias('event_emitting_workspace'),",
        "    F.col('e.executingUPN'),",
        "    F.col('e.executingPrincipalType'),",
        "    F.col('e.executingPrincipalId'),",
        "    F.col('e.callerIPAddress'),",
        "    F.col('e.originatingApp'),",
        "    F.col('e.accessStartTime'),",
        "    F.col('e.accessEndTime'),",
        "    F.col('e.operationName'),",
        "    F.col('e.operationCategory'),",
        "    F.col('e.serviceEndpoint'),",
        "    F.col('e.httpStatusCode'),",
        "    F.col('e.contentLength').alias('bytes'),",
        "    F.col('e.correlationId'),",
        "    F.col('e.isShortcut'),",
        "    F.col('e.accessedViaResource').alias('shortcut_path_consumer'),",
        "    F.col('e.Resource').alias('resolved_target_resource'),",
        "    F.col('d.source_workspace_name').alias('shortcut_consumer_workspace'),",
        "    F.col('d.source_item_name').alias('shortcut_consumer_lakehouse'),",
        "    F.col('d.target_type'),",
        "    F.col('d.target_workspace_id'),",
        "    F.col('d.target_workspace_name'),",
        "    F.col('d.target_item_id'),",
        "    F.col('d.target_item_name'),",
        "    F.col('d.target_path'),",
        "    F.col('d.target_connection_id'),",
        "    F.col('d.target_location'),",
        "    F.col('d.target_subpath'),",
        ")",
        "",
        "# overwrite — silver is a derived view; recomputing is cheap and keeps logic simple",
        "(enriched.write.format('delta')",
        "    .mode('overwrite').option('overwriteSchema','true')",
        "    .saveAsTable(TBL['silver']))",
        "",
        "print('Silver rebuilt. Sample:')",
        "spark.table(TBL['silver']).orderBy(F.col('accessStartTime').desc()).show(10, truncate=False)",
    ),
])

# ---------------- 05_gold_queries ----------------
nb05 = nb([
    md("# 05 — Gold queries (samples)",
       "",
       "Use these as starting points; pin to Power BI via the SQL analytics endpoint of `ObservabilityLH`."),
    LOAD_CFG,
    md("## Top users copying shortcut-backed data in the last 24h"),
    code(
        "spark.sql(f'''",
        "SELECT executingUPN, target_type,",
        "       COUNT(*)              AS ops,",
        "       SUM(COALESCE(bytes,0)) AS bytes_read,",
        "       COLLECT_SET(originatingApp)        AS apps,",
        "       COLLECT_SET(callerIPAddress)       AS ips,",
        "       COLLECT_SET(shortcut_path_consumer) AS shortcut_paths",
        "FROM {TBL['silver']}",
        "WHERE accessStartTime > current_timestamp() - INTERVAL 1 DAY",
        "  AND operationCategory = 'Read'",
        "GROUP BY executingUPN, target_type",
        "ORDER BY ops DESC",
        "''').show(50, truncate=False)",
    ),
    md("## Cross-workspace data egress (consumer ws ≠ target ws)"),
    code(
        "spark.sql(f'''",
        "SELECT shortcut_consumer_workspace, target_workspace_id,",
        "       executingUPN, originatingApp,",
        "       COUNT(*) AS ops",
        "FROM {TBL['silver']}",
        "WHERE accessStartTime > current_timestamp() - INTERVAL 7 DAY",
        "  AND target_type = 'OneLake'",
        "  AND shortcut_consumer_workspace IS NOT NULL",
        "GROUP BY shortcut_consumer_workspace, target_workspace_id, executingUPN, originatingApp",
        "ORDER BY ops DESC",
        "''').show(50, truncate=False)",
    ),
    md("## Suspicious external copies (PutBlobFromURL / CopyBlob via shortcut)"),
    code(
        "spark.sql(f'''",
        "SELECT accessStartTime, executingUPN, callerIPAddress, originatingApp,",
        "       operationName, shortcut_path_consumer, resolved_target_resource,",
        "       target_type, target_location",
        "FROM {TBL['silver']}",
        "WHERE operationName IN ('PutBlobFromURL','CopyBlob','AbortCopyBlob')",
        "  AND accessStartTime > current_timestamp() - INTERVAL 7 DAY",
        "ORDER BY accessStartTime DESC",
        "''').show(50, truncate=False)",
    ),
    md("## External-tool access (azcopy, Storage Explorer, …) on any shortcut"),
    code(
        "spark.sql(f'''",
        "SELECT accessStartTime, executingUPN, callerIPAddress, originatingApp,",
        "       operationName, shortcut_path_consumer, resolved_target_resource",
        "FROM {TBL['silver']}",
        "WHERE accessStartTime > current_timestamp() - INTERVAL 1 DAY",
        "  AND originatingApp RLIKE '(?i)(azcopy|storage.explorer|powershell|curl|python-requests|rclone)'",
        "ORDER BY accessStartTime DESC",
        "''').show(100, truncate=False)",
    ),
])

# ---------------- write all ----------------
for fname, doc in [
    ('01_setup.ipynb', nb01),
    ('02_bronze_union_diagnostics.ipynb', nb02),
    ('03_dim_shortcuts_map.ipynb', nb03),
    ('04_silver_enriched_access.ipynb', nb04),
    ('05_gold_queries.ipynb', nb05),
]:
    path = OUT / 'notebooks' / fname
    path.parent.mkdir(parents=True, exist_ok=True)
    new_text = json.dumps(doc, indent=1)
    old_text = path.read_text(encoding='utf-8') if path.exists() else None
    if old_text == new_text:
        print(f'skip  {path} (unchanged)')
        continue
    path.write_text(new_text, encoding='utf-8')
    print(f'wrote {path}')
